import Head from "next/head";
import Main from "../components/Main";

const Home = () => {
  return  (
        <>
          <Head>
            <title>React-boots</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <Main />
        </>
      )
  }

export default Home;
