import { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Main from "../components/Main";
import { CardType } from "../types/types";

type PropsType = {
  data: Array<CardType>
}

const Home: NextPage<PropsType> = (data) => {
  const [item, setItem] = useState<Array<CardType>>([])

  const addToDrawer = (obj: CardType) => {
    item.find((el: CardType) => el.id === obj.id) 
    ? setItem(item.filter((el: CardType) => el.id !== obj.id)) 
    : setItem(prev => [...prev, obj])
  }

  return (
    <>
      <Head>
        <title>React-boots</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header item={item}/>
      <Main {...data} addToDrawer={addToDrawer} />
      <Footer />
    </>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('https://630f1ba6498924524a860c3f.mockapi.io/users')
  const data = await res.json()
  return {data}
}

export default Home;
