import Head from "next/head";
import React, { useState } from "react";
import { FC } from "react";
import Draw from "../components/Draw";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Main from "../components/Main";

const Home: FC = () => {
  
  return (
    <>
      <Head>
        <title>React-boots</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </>
  );
};
export default Home;
